source $HOME/.nix-profile/etc/profile.d/nix.sh"
export EDITOR=vim

source @fzf_src@/shell/key-bindings.bash
export FZF_TMUX=0

export PATH="$HOME/bin:$HOME/.nix-profile/bin:$PATH"

export JAVA_HOME="@jdk@"
